# https://travis-ci.org/

language: java
jdk: oraclejdk8

# Default: 'mvn test -B'
# Override: integration-test
script:
  - mvn verify -B

after_success:
  # Workaround because goal 'jacoco:report@post-integration-test' not working
  - mvn verify -DskipTests -B
  # Publish to Coveralls.io
  - mvn coveralls:report
