# https://travis-ci.org/

language: java
jdk: oraclejdk8

before_script:
  - export JAVA_OPTS=-Xmx1g

before_install:
  # Codecov.io: install
  - pip install --user codecov

# Default: 'mvn test -B'
# Override: add integration-test Maven phase
script:
  - mvn verify -B

after_success:
  # JaCoCo: workaround because goal 'jacoco:report@post-integration-test' not working
  - mvn verify -DskipTests -B
  # Coveralls.io: publish
  - mvn coveralls:report
  # Codecov.io: install
  - codecov

after_failure:
  # show memory usage again
  - sudo free -m -t
  # show actions of the OOM killer
  - sudo dmesg