# Note: "external config" = requires to be set by external configuration
# See: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

spring:
    aop:
        # Disable proxies
        auto: false
        proxy-target-class: false