spring:
    aop:
        # Disable proxies
        auto: false
        proxy-target-class: false
    datasource:
        #url: external config
    jpa:
        hibernate:
            # Lower/underscore conversion of table/column name
            naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
                # globally_quoted_identifiers: true
                # default_schema: public
                use_sql_comments: false
                show_sql: true
                format_sql: true
    mail:
        test-connection: true
        #host: external config
        #port: external config
        #username: external config
        #password: external config
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            #mail.smtp.ssl.trust: smtp.gmail.com
